export enum Department {
  FRONT_DESK = 'FRONT_DESK',
  HOUSEKEEPING = 'HOUSEKEEPING',
  MAINTENANCE = 'MAINTENANCE',
  RESTAURANT = 'RESTAURANT',
  MANAGEMENT = 'MANAGEMENT',
  SECURITY = 'SECURITY',
  VALET = 'VALET',
}
