import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Employee } from '../entities';
import { Department, StaffStatus } from '@app/contracts/staff-service';

@Injectable()
export class EmployeesSeeder {
  constructor(
    @InjectRepository(Employee)
    private readonly employeeRepository: Repository<Employee>,
  ) {}

  async seed(): Promise<void> {
    const employees: Array<Omit<Employee, 'id' | 'createdAt' | 'updatedAt'>> = [
      {
        employeeId: 'EMP001',
        name: 'Mary Johnson',
        department: Department.HOUSEKEEPING,
        position: 'Housekeeping Supervisor',
        shift: 'Morning',
        assignedRooms: 15,
        completedRooms: 14,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Floor 2',
      },
      {
        employeeId: 'EMP003',
        name: 'Emily Brown',
        department: Department.HOUSEKEEPING,
        position: 'Room Attendant',
        shift: 'Morning',
        assignedRooms: 12,
        completedRooms: 11,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Floor 3',
      },
      {
        employeeId: 'EMP007',
        name: 'Sarah Wilson',
        department: Department.HOUSEKEEPING,
        position: 'Room Attendant',
        shift: 'Morning',
        assignedRooms: 10,
        completedRooms: 10,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Floor 1',
      },
      {
        employeeId: 'EMP008',
        name: 'Patricia Sanders',
        department: Department.HOUSEKEEPING,
        position: 'Room Attendant',
        shift: 'Afternoon',
        assignedRooms: 11,
        completedRooms: 9,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Floor 4',
      },
      {
        employeeId: 'EMP009',
        name: 'Ellen Reynolds',
        department: Department.HOUSEKEEPING,
        position: 'Room Attendant',
        shift: 'Morning',
        assignedRooms: 13,
        completedRooms: 9,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Floor 2',
      },
      {
        employeeId: 'EMP010',
        name: 'Rachel Dixon',
        department: Department.HOUSEKEEPING,
        position: 'Room Attendant',
        shift: 'Afternoon',
        assignedRooms: 10,
        completedRooms: 6,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Floor 5',
      },
      {
        employeeId: 'EMP011',
        name: 'Isabella Turner',
        department: Department.HOUSEKEEPING,
        position: 'Laundry Attendant',
        shift: 'Morning',
        assignedRooms: 8,
        completedRooms: 5,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Laundry',
      },
      {
        employeeId: 'EMP002',
        name: 'James Smith',
        department: Department.FRONT_DESK,
        position: 'Front Desk Agent',
        shift: 'Day',
        assignedRooms: 0,
        completedRooms: 0,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Reception',
      },
      {
        employeeId: 'EMP012',
        name: 'Andrea Foster',
        department: Department.FRONT_DESK,
        position: 'Front Desk Manager',
        shift: 'Morning',
        assignedRooms: 0,
        completedRooms: 0,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Reception',
      },
      {
        employeeId: 'EMP004',
        name: 'Louis Foster',
        department: Department.MAINTENANCE,
        position: 'Maintenance Technician',
        shift: 'Full Time',
        assignedRooms: 7,
        completedRooms: 6,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Maintenance Room',
      },
      {
        employeeId: 'EMP013',
        name: 'Michael Santos',
        department: Department.MAINTENANCE,
        position: 'Electrician',
        shift: 'Day',
        assignedRooms: 5,
        completedRooms: 5,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Floor 3',
      },
      {
        employeeId: 'EMP014',
        name: 'George Miller',
        department: Department.MAINTENANCE,
        position: 'Plumber',
        shift: 'Day',
        assignedRooms: 6,
        completedRooms: 4,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Floor 1',
      },
      {
        employeeId: 'EMP005',
        name: 'Amanda Davis',
        department: Department.RESTAURANT,
        position: 'Waitress',
        shift: 'Evening',
        assignedRooms: 0,
        completedRooms: 0,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Restaurant',
      },
      {
        employeeId: 'EMP015',
        name: 'Diana Carter',
        department: Department.RESTAURANT,
        position: 'Head Waitress',
        shift: 'Lunch',
        assignedRooms: 0,
        completedRooms: 0,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Restaurant',
      },
      {
        employeeId: 'EMP016',
        name: 'Frank Rice',
        department: Department.RESTAURANT,
        position: 'Chef',
        shift: 'Full Time',
        assignedRooms: 0,
        completedRooms: 0,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Kitchen',
      },
      {
        employeeId: 'EMP006',
        name: 'Robert Silver',
        department: Department.SECURITY,
        position: 'Security Guard',
        shift: 'Night',
        assignedRooms: 0,
        completedRooms: 0,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Main Entrance',
      },
      {
        employeeId: 'EMP017',
        name: 'Michael Taylor',
        department: Department.SECURITY,
        position: 'Security Guard',
        shift: 'Day',
        assignedRooms: 0,
        completedRooms: 0,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Parking',
      },
      {
        employeeId: 'EMP018',
        name: 'Peter Graham',
        department: Department.VALET,
        position: 'Valet Attendant',
        shift: 'Day',
        assignedRooms: 0,
        completedRooms: 0,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Valet Station',
      },
      {
        employeeId: 'EMP019',
        name: 'Jason Miller',
        department: Department.VALET,
        position: 'Valet Attendant',
        shift: 'Evening',
        assignedRooms: 0,
        completedRooms: 0,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Valet Station',
      },
      {
        employeeId: 'EMP020',
        name: 'Gabrielle Oliver',
        department: Department.MANAGEMENT,
        position: 'Hotel Manager',
        shift: 'Full Time',
        assignedRooms: 0,
        completedRooms: 0,
        status: StaffStatus.ACTIVE,
        currentLocation: 'Office',
      },
      {
        employeeId: 'EMP021',
        name: 'Richard Nelson',
        department: Department.HOUSEKEEPING,
        position: 'Room Attendant',
        shift: 'Morning',
        assignedRooms: 0,
        completedRooms: 0,
        status: StaffStatus.ON_LEAVE,
        currentLocation: 'N/A',
      },
    ];

    for (const employeeData of employees) {
      const existingEmployee = await this.employeeRepository.findOne({
        where: { employeeId: employeeData.employeeId },
      });

      if (!existingEmployee) {
        await this.employeeRepository.save(employeeData);
      }
    }
  }
}
