export enum InventoryCategory {
  LINENS = 'LINENS',
  AMENITIES = 'AMENITIES',
  CLEANING_SUPPLIES = 'CLEANING_SUPPLIES',
  FOOD_BEVERAGE = 'FOOD_BEVERAGE',
  MAINTENANCE = 'MAINTENANCE',
  OFFICE_SUPPLIES = 'OFFICE_SUPPLIES',
  FURNITURE = 'FURNITURE',
  ELECTRONICS = 'ELECTRONICS',
}
