export enum PaymentMethod {
  CASH = 'CASH',
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  BANK_TRANSFER = 'BANK_TRANSFER',
  MOBILE_PAYMENT = 'MOBILE_PAYMENT',
  CRYPTOCURRENCY = 'CRYPTOCURRENCY',
  CHECK = 'CHECK',
  GIFT_CARD = 'GIFT_CARD',
}
