export enum MaintenanceType {
  ELECTRICAL = 'ELECTRICAL',
  PLUMBING = 'PLUMBING',
  HVAC = 'HVAC',
  FURNITURE = 'FURNITURE',
  APPLIANCES = 'APPLIANCES',
  STRUCTURAL = 'STRUCTURAL',
  COSMETIC = 'COSMETIC',
}
