export enum ReportType {
  OCCUPANCY = 'OCCUPANCY',
  REVENUE = 'REVENUE',
  STAFF = 'STAFF',
  GUEST_SATISFACTION = 'GUEST_SATISFACTION',
  MAINTENANCE = 'MAINTENANCE',
  FINANCIAL = 'FINANCIAL',
  CUSTOM = 'CUSTOM',
}
