export enum RequestType {
  TOWELS = 'TOWELS',
  ROOM_SERVICE = 'ROOM_SERVICE',
  MAINTENANCE = 'MAINTENANCE',
  HOUSEKEEPING = 'HOUSEKEEPING',
  CONCIERGE = 'CONCIERGE',
  TECHNICAL_SUPPORT = 'TECHNICAL_SUPPORT',
  OTHER = 'OTHER',
}
