export enum AnalyticsMetric {
  OCCUPANCY_RATE = 'OCCUPANCY_RATE',
  REVENUE_PER_ROOM = 'REVENUE_PER_ROOM',
  CUSTOMER_SATISFACTION = 'CUSTOMER_SATISFACTION',
  AVERAGE_STAY_LENGTH = 'AVERAGE_STAY_LENGTH',
  REPEAT_CUSTOMER_RATE = 'REPEAT_CUSTOMER_RATE',
  STAFF_EFFICIENCY = 'STAFF_EFFICIENCY',
}
