export enum AuditResource {
  USER = 'USER',
  ROLE = 'ROLE',
  PERMISSION = 'PERMISSION',

  RESERVATION = 'RESERVATION',
  ROOM = 'ROOM',
  GUEST = 'GUEST',

  INVOICE = 'INVOICE',
  PAYMENT = 'PAYMENT',
  BILLING = 'BILLING',

  EMPLOYEE = 'EMPLOYEE',
  SHIFT = 'SHIFT',
  ATTENDANCE = 'ATTENDANCE',
  HOUSEKEEPING = 'HOUSEKEEPING',
  MAINTENANCE = 'MAINTENANCE',

  RESTAURANT = 'RESTAURANT',
  MENU_ITEM = 'MENU_ITEM',
  ROOM_SERVICE = 'ROOM_SERVICE',
  EVENT = 'EVENT',
  VENUE = 'VENUE',
  RECREATIONAL = 'RECREATIONAL',

  INVENTORY = 'INVENTORY',
  SUPPLIER = 'SUPPLIER',
  PARKING = 'PARKING',

  GUEST_REQUEST = 'GUEST_REQUEST',
  EMPLOYEE_REQUEST = 'EMPLOYEE_REQUEST',

  REPORT = 'REPORT',
  ANALYTICS = 'ANALYTICS',

  CONFIGURATION = 'CONFIGURATION',
  NOTIFICATION = 'NOTIFICATION',
  AUDIT_LOG = 'AUDIT_LOG',

  SYSTEM = 'SYSTEM',
  OTHER = 'OTHER',
}
