export enum AuditAction {
  // CRUD Operations
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',

  // Authentication Actions
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PASSWORD_RESET = 'PASSWORD_RESET',

  // Reservation Actions
  CHECK_IN = 'CHECK_IN',
  CHECK_OUT = 'CHECK_OUT',
  CANCEL_RESERVATION = 'CANCEL_RESERVATION',
  MODIFY_RESERVATION = 'MODIFY_RESERVATION',

  // Payment Actions
  PAYMENT_PROCESSED = 'PAYMENT_PROCESSED',
  REFUND_ISSUED = 'REFUND_ISSUED',
  INVOICE_GENERATED = 'INVOICE_GENERATED',

  // Status Changes
  STATUS_CHANGE = 'STATUS_CHANGE',
  APPROVAL = 'APPROVAL',
  REJECTION = 'REJECTION',

  // System Actions
  SYSTEM_CONFIG_CHANGE = 'SYSTEM_CONFIG_CHANGE',
  PERMISSION_GRANTED = 'PERMISSION_GRANTED',
  PERMISSION_REVOKED = 'PERMISSION_REVOKED',
  ROLE_ASSIGNED = 'ROLE_ASSIGNED',
  ROLE_REMOVED = 'ROLE_REMOVED',

  // File Operations
  FILE_UPLOAD = 'FILE_UPLOAD',
  FILE_DOWNLOAD = 'FILE_DOWNLOAD',
  FILE_DELETE = 'FILE_DELETE',

  // Report Generation
  REPORT_GENERATED = 'REPORT_GENERATED',
  EXPORT = 'EXPORT',

  // Custom Actions
  CUSTOM = 'CUSTOM',
}
