export enum ConfigCategory {
  GENERAL = 'GENERAL',
  HOTEL = 'HOTEL',
  SYSTEM = 'SYSTEM',
  SECURITY = 'SECURITY',
  PAYMENT = 'PAYMENT',
  NOTIFICATION = 'NOTIFICATION',
  INTEGRATION = 'INTEGRATION',
  APPEARANCE = 'APPEARANCE',
}
